# Permite doar trafic HTTP de la frontend la backend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: permite-frontend-la-backend
  namespace: aplicatie
spec:
  podSelector:
    matchLabels:
      tier: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: frontend
    ports:
    - protocol: TCP
      port: 8080
